### ISSUE TITLE
啊这 还能这么玩 学到了.jpg

### ISSUE THREAD

**Issue by XenoAmess** [RimoChan/rimochan#1]
这就去给自己也整一个

**Comment by RimoChan** [comment]
好啊！
<sub>(多放色图！)</sub>

**Comment by XenoAmess** [comment]
那个 虽然 可能你不在意 但是你commit的id 身份暴露了

**Comment by XenoAmess** [comment]
![chrome_2020-08-30_18-44-36](https://user-images.githubusercontent.com/17455337/91657086-e8fa7480-eaf0-11ea-990c-59f9cc0b6831.png)

**Comment by RimoChan** [comment]
名字无所谓的，不过我奇怪的是我提交的时候用了私钥但是GitHub没有把commit的作者链接到我的帐号上……
