### ISSUE TITLE
想看老婆的本子.png

### ISSUE THREAD

**Issue by kazura233** [RimoChan/rimochan#3]
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/26360761/232438773-ac83957b-cdf9-4085-b88e-ce48e76a6178.png">

**Comment by RimoChan** [comment]
那之后放到pixiv上吧！

**Comment by RimoChan** [comment]
不对！

**Comment by RimoChan** [comment]
![image](https://user-images.githubusercontent.com/20064807/232440626-eb6a7102-98ed-446d-aa18-42f721934ab9.png)
