### ISSUE TITLE
莉沫酱独占头条了！（贵仓库的align=right属性似乎不生效了）

### ISSUE THREAD

**Issue by GhostFrankWu** [RimoChan/rimochan#4]
Github现在疑似不给`webp`和`png`的嵌入图像的align属性生效了，本地Chrome125以及Edge查看时显示都有问题。

推断问题出在Github，因为：
[9月5日的快照依旧正常显示](https://web.archive.org/web/20240905130310/https://github.com/RimoChan) 
[9月11日的快照就不一样了](https://web.archive.org/web/20240911051308/https://github.com/RimoChan)
~~WebArchive的所有资源都是一同快照的，等待资源加载可能非常缓慢~~

一个其他同样不生效的仓库：  
https://github.com/xJoyLu

`jpeg`似乎也有bug：  
https://github.com/zqqcee  

但是其他用`gif`格式的仓库效果依旧很好：  
https://github.com/eryajf
https://github.com/Leecason
https://github.com/LouisLiu00

如果您考虑修复显示效果，一种修复建议是[将webp换为体积大一点的gif](https://github.com/GhostFrankWu/GhostFrankWu/commit/5f6f7145a97eba9aaaccb4027f292e54be576eec)

截图FYI:
![image](https://github.com/user-attachments/assets/6681497b-7481-4a1b-8b9b-f9cf831ec8ac)
![image](https://github.com/user-attachments/assets/71925101-9362-4ac6-b656-021a159055e5)

**Comment by RimoChan** [comment]
GitHub太坏了！我要建立UnvHub把GitHub打下去！

**Comment by RimoChan** [comment]
咦，等等，你的显示也是错的，可能gif也没有效果了？
![image](https://github.com/user-attachments/assets/c8f7aa79-05b7-4dec-8b73-f6b9f0cf31c3)

**Comment by GhostFrankWu** [comment]
奇怪，我的主页这边看似乎是正常的？ 包括第一条里面那几个gif的link也还是正常的，您的浏览器也是Chrome吗

![image](https://github.com/user-attachments/assets/214bce84-c710-42c0-a5a4-3bdec253d04b)

**Comment by GhostFrankWu** [comment]
https://github.com/RimoChan/rimochan/commit/e93b3714c6e0a0e3a08969e3161866f8a6303a2d 现在看起来已经正常了，好耶

**Comment by RimoChan** [comment]
不对，我看到的你和我都是有问题的，它编译出来的html是有align的，所以不是Github的问题，是Chrome的问题。我的是Chrome 128.0.6613.138。

**Comment by RimoChan** [comment]
Firefox就是正常的

**Comment by RimoChan** [comment]
啊奇怪，我这边突然现在又好了，不知道发生了什么2333

**Comment by GhostFrankWu** [comment]
目前来看我更倾向于是GitHub做出了什么锅然后自己悄悄hotfix了，WebArchive不会说谎（）
